# Generated by Django 3.2.9 on 2021-12-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211205_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branch_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_number',
            new_name='number',
        ),
    ]
