# Generated by Django 3.2.9 on 2021-12-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211208_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cutoff_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
