# Generated by Django 3.2.9 on 2021-12-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_cutoff_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='Inactiva', max_length=50),
        ),
    ]
