# Generated by Django 3.2.9 on 2021-12-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reference_number',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='auth_number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
